file(TO_NATIVE_PATH "${CMAKE_SOURCE_DIR}" VS_DEBUGGER_WORKING_DIRECTORY)
file(TO_NATIVE_PATH "${CMAKE_SOURCE_DIR}/luarocks/lua.bat" VS_DEBUGGER_COMMAND)

set_target_properties(${target_name} PROPERTIES
    VS_DEBUGGER_COMMAND           "${VS_DEBUGGER_COMMAND}"
    VS_DEBUGGER_COMMAND_ARGUMENTS "samples/01-face_detection.lua"
    VS_DEBUGGER_WORKING_DIRECTORY "${VS_DEBUGGER_WORKING_DIRECTORY}"
    VS_DEBUGGER_ENVIRONMENT       "BUILD_TYPE=$(Configuration)"
)

set_property(DIRECTORY "${CMAKE_SOURCE_DIR}" PROPERTY VS_STARTUP_PROJECT ${target_name})
